version: "3.9"

services:
  mongodb:
    container_name: mongodb-wichat_es3a
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  authservice:
    container_name: authservice-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/authservice:latest
    profiles: ["dev", "prod"]
    build: ./users/authservice
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    env_file: ./users/authservice/.env

  userservice:
    container_name: userservice-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/userservice:latest
    profiles: ["dev", "prod"]
    build: ./users/userservice
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    env_file: ./users/userservice/.env

  llmservice:
    container_name: llmservice-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/llmservice:latest
    profiles: ["dev", "prod"]
    build: ./llmservice
    ports:
      - "8003:8003"
    networks:
      - mynetwork
    env_file: ./llmservice/.env

  gatewayservice:
    container_name: gatewayservice-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/gatewayservice:latest
    profiles: ["dev", "prod"]
    build: ./gatewayservice
    depends_on:
      - mongodb
      - userservice
      - authservice
      - llmservice
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    env_file: ./gatewayservice/.env

  webapp:
    container_name: webapp-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/webapp:latest
    profiles: ["dev", "prod"]
    build:
      context: ./webapp
      args:
        LLM_API_KEY: ${LLM_API_KEY}
    depends_on:
      - gatewayservice
    ports:
      - "3000:3000"
    env_file: ./webapp/.env

  prometheus:
    image: prom/prometheus
    container_name: prometheus-wichat_es3a
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - gatewayservice

  grafana:
    image: grafana/grafana
    container_name: grafana-wichat_es3a
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on:
      - prometheus

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:

networks:
  mynetwork:
    driver: bridge
