version: "3.9"

services:
  mongodb:
    container_name: mongodb-wichat_es3a
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  authservice:
    container_name: authservice-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/authservice:latest
    build: ./users/authservice
    profiles: ["dev", "prod"]
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: ${MONGO_URI}

  userservice:
    container_name: userservice-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/userservice:latest
    build: ./users/userservice
    profiles: ["dev", "prod"]
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: ${MONGO_URI}

  historic:
    container_name: historic-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/historic:latest
    profiles: ["dev", "prod"]
    build: ./historicservice
    ports:
      - "8007:8007"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: ${MONGO_URI}


  questionservice:
    container_name: questionservice-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/questionservice:latest
    build: ./questionservice
    profiles: ["dev", "prod"]
    depends_on:
      - mongodb
    ports:
      - "8004:8004"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: ${MONGO_URI}

  cardservice:
    container_name: cardservice-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/cardservice:latest
    profiles: ["dev", "prod"]
    build: ./cardservice
    ports:
      - "8008:8008"
    networks:
      - mynetwork

  llmservice:
    container_name: llmservice-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/llmservice:latest
    build: ./llmservice
    profiles: ["dev", "prod"]
    ports:
      - "8003:8003"
    networks:
      - mynetwork
    environment:
      LLM_API_KEY: ${LLM_API_KEY}

  gatewayservice:
    container_name: gatewayservice-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/gatewayservice:latest
    build: ./gatewayservice
    profiles: ["dev", "prod"]
    depends_on:
      - userservice
      - authservice
      - llmservice
      - questionservice
      - historic
      - cardservice
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
      LLM_SERVICE_URL: http://llmservice:8003
      QUESTION_SERVICE_URL: http://questionservice:8004
      HISTORIC_SERVICE_URL: http://historic:8007
      CARD_SERVICE_URL: http://cardservice:8008
      
  gateway-api-service:
    container_name: gateway-api-service-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/gateway-api-service:latest
    build: ./gateway-api-service
    profiles: ["dev", "prod"]
    depends_on:
      - mongodb
      - userservice
      - questionservice
    ports:
      - "8006:8006"
    networks:
      - mynetwork
    environment:
      USER_SERVICE_URL: http://userservice:8001
      QUESTION_SERVICE_URL: http://questionservice:8004

  webapp:
    container_name: webapp-wichat_es3a
    image: ghcr.io/arquisoft/wichat_es3a/webapp:latest
    build:
      context: ./webapp
      args:
        REACT_APP_LLM_API_KEY: ${LLM_API_KEY}
        REACT_APP_API_ENDPOINT: http://wichatdeluxe.duckdns.org:8000
    profiles: ["dev", "prod"]
    depends_on:
      - gatewayservice
    ports:
      - "3000:3000"
    environment:
      REACT_APP_LLM_API_KEY: ${LLM_API_KEY}
      REACT_APP_API_ENDPOINT: http://wichatdeluxe.duckdns.org:8000

  prometheus:
    image: prom/prometheus
    container_name: prometheus-wichat_es3a
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - gatewayservice

  grafana:
    image: grafana/grafana
    container_name: grafana-wichat_es3a
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SERVER_HTTP_PORT: 9091
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    ports:
      - "9091:9091"
    depends_on:
      - prometheus

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:

networks:
  mynetwork:
    driver: bridge
