openapi: 3.0.0
info:
  title: Gateway API Service
  description: API Gateway service that exposes only /api/* endpoints
  version: 1.0.0
servers:
  - url: http://localhost:8006
    description: Development server
  - url: http://SOMEIP:8006
    description: Production server
paths:
  /api/users:
    get:
      summary: Get all users from the database
      operationId: getUsers
      responses:
        '200':
          description: Successfully retrieved users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: User ID in the database
                      example: 65f756db3fa22d227a4b7c7d
                    username:
                      type: string
                      description: Username
                      example: student
                    password:
                      type: string
                      description: Hashed password
                      example: $2b$10$ZKdNYLWFQxzt5Rei/YTc/OsZNi12YiWz30JeUFHNdAt7MyfmkTuvC
                    createdAt:
                      type: string
                      description: User creation date
                      example: '2024-03-17T20:47:23.935Z'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information
                    example: Error interno

  /api/questions:
    get:
      summary: Get all questions from the database
      operationId: getQuestions
      responses:
        '200':
          description: Successfully retrieved questions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: Question ID in the database
                      example: 65f756db3fa22d227a4b7c7e
                    question:
                      type: string
                      description: The question text
                      example: "¿Cuál es la capital de Francia?"
                    options:
                      type: array
                      items:
                        type: string
                      description: Available answer options
                      example: ["París", "Londres", "Berlín", "Madrid"]
                    correctAnswer:
                      type: string
                      description: The correct answer
                      example: "París"
                    category:
                      type: string
                      description: Question category
                      example: "geografía"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information
                    example: Error interno