name: CI for wichat_es3a

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - run: npm --prefix users/authservice ci
    - run: npm --prefix users/userservice ci
    - run: npm --prefix questionservice ci
    - run: npm --prefix historicservice ci
    - run: npm --prefix llmservice ci
    - run: npm --prefix gatewayservice ci
    - run: npm --prefix gateway-api-service ci
    - run: npm --prefix webapp ci
    - run: npm --prefix users/authservice test -- --coverage
    - run: npm --prefix users/userservice test -- --coverage
    - run: npm --prefix questionservice test -- --coverage
    - run: npm --prefix historicservice test -- --coverage
    - run: npm --prefix llmservice test -- --coverage
      env:
        LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
    - run: npm --prefix gatewayservice test -- --coverage
    - run: npm --prefix gateway-api-service test -- --coverage
    - run: npm --prefix webapp test -- --coverage
    - name: Analyze with SonarCloud
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  e2e-tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - run: npm --prefix users/authservice install
    - run: npm --prefix users/userservice install
    - run: npm --prefix questionservice install
    - run: npm --prefix llmservice install
    - run: npm --prefix gatewayservice install
    - run: npm --prefix gateway-api-service install
    - run: npm --prefix webapp install
    - run: npm --prefix webapp run build
    - run: npm --prefix webapp run test:e2e

  docker-push-webapp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          API_ENDPOINT: http://wichatdeluxe.duckdns.org:8000
          API_REST_ENDPOINT: http://wichatdeluxe.duckdns.org:8006
        with:
          name: arquisoft/wichat_es3a/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: webapp
          buildargs: |
            LLM_API_KEY
            REACT_APP_API_ENDPOINT=${{ env.API_ENDPOINT }}
            REACT_APP_API_REST_ENDPOINT=${{ env.API_REST_ENDPOINT }}

  docker-push-authservice:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: arquisoft/wichat_es3a/authservice
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: users/authservice
          platforms: linux/amd64,linux/arm64

  docker-push-userservice:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: arquisoft/wichat_es3a/userservice
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: users/userservice

  docker-push-llmservice:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: arquisoft/wichat_es3a/llmservice
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: llmservice

  docker-push-questionservice:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: arquisoft/wichat_es3a/questionservice
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: questionservice

  docker-push-gatewayservice:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Update OpenAPI configuration
        run: |
          DEPLOY_HOST=${{ secrets.DEPLOY_HOST }}
          sed -i "s/SOMEIP/${DEPLOY_HOST}/g" gatewayservice/openapi.yaml
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: arquisoft/wichat_es3a/gatewayservice
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: gatewayservice

  docker-push-gateway-api-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: arquisoft/wichat_es3a/gateway-api-service
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: gateway-api-service

  deploy:
    runs-on: ubuntu-latest
    needs: [
      docker-push-userservice,
      docker-push-authservice,
      docker-push-llmservice,
      docker-push-questionservice,
      docker-push-gatewayservice,
      docker-push-gateway-api-service,
      docker-push-webapp
    ]
    steps:
      - name: Deploy over SSH
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          command: |
            cd wichat_es3a
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            export LLM_API_KEY="${{ secrets.LLM_API_KEY }}"
            export MONGO_URI="${{ secrets.MONGO_URI }}"
            docker compose --profile prod pull
            docker compose --profile prod down
            docker compose --profile prod up -d
